### ISSUE TITLE
curaengine shows a command window in Windows

### ISSUE THREAD

**Issue by nraynaud** [nraynaud/FusedCura#2]

**Comment by ghost** [comment]
![cura engine command window](https://user-images.githubusercontent.com/32071492/44223851-19307e00-a189-11e8-9a8f-11e37c05093d.PNG)

This happens every time you change a parameter in the settings tab.

**Comment by nraynaud** [comment]
I think you might have selected cura.exe instead of curaengine.exe in the FusedCura configuration panel.
![curaengine](https://user-images.githubusercontent.com/46941/44224226-1aae7600-a18a-11e8-9a32-52b8657591ce.png)

**Comment by ghost** [comment]
that's is, my fault

**Comment by nraynaud** [comment]
no pb
